-- --------------------------------------
-- TSSI-2020. administracion de BD
-- DDL: Create table
-- Tabla: DatosBase
-- --------------------------------------
create table DatosBase (
    Jurisdiccion varchar(255),
    CUE_Anexo varchar(255),
    Nombre varchar(255),
    Sector varchar(255),
    Ambito varchar(255),
    Domicilio varchar(255),
    CP varchar(255),
    Codigo_de_area varchar(255),
    Telefono varchar(255),
    Codigo_localidad varchar(255),
    Localidad varchar(255),
    Departamento varchar(255),
    Mail varchar(255),
    Ed_Comun varchar(255),
    Ed_Especial varchar(255),
    Ed_Adultos varchar(255),
    Ed_Artistica varchar(255),
    Ed_Hospitalaria_Domiciliaria varchar(255),
    Ed_Intercultural_Bilingue varchar(255),
    Ed_Contexto_de_Encierro varchar(255),
    Ed_Comun_Jardin_maternal varchar(255),
    Ed_Comun_Inicial varchar(255),
    Ed_Comun_Primaria varchar(255),
    Ed_Comun_Secundaria varchar(255),
    Ed_Comun_Secundaria_Tecnica_INET varchar(255),
    Ed_Comun_Superior_no_Universitario varchar(255),
    Ed_Comun_Superior_No_Universitario_INET varchar(255),
    Ed_Artistica_Secundaria varchar(255),
    Ed_Artistica_Superior_no_Universitario varchar(255),
    Ed_Artistica_Cursos_y_Talleres varchar(255),
    Ed_Especial_Educacion_Temprana varchar(255),
    Ed_Especial_Inicial varchar(255),
    Ed_Especial_Primaria varchar(255),
    Ed_Especial_Secundaria varchar(255),
    Ed_Especial_Integracion varchar(255),
    Ed_Adultos_Primaria varchar(255),
    Ed_Adultos_EGB3 varchar(255),
    Ed_Adultos_Secundaria varchar(255),
    Ed_Adultos_Alfabetizacion varchar(255),
    Ed_Adultos_Formacion_Profesional varchar(255),
    Ed_Adultos_Formacion_Profesional_INET_ varchar(255),
    Ed_Hospitalaria_Domiciliaria_Inicial varchar(255),
    Ed_Hospitalaria_Domiciliaria_Primaria varchar(255),
    Ed_Hospitalaria_Domiciliaria_Secundaria varchar(255),
    Servicios_complementarios varchar(255)
);