drop view if exists Servicios;
create view Servicios as
          select  1 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Jardin maternal" = 'X'             
union all select  2 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Inicial"    = 'X'                     
union all select  3 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Primaria"         = 'X'               
union all select  4 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Secundaria"            = 'X'         
union all select  5 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Secundaria Tecnica INET"      = 'X'   
union all select  6 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Superior no Universitario"     = 'X' 
union all select  7 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Común Superior No Universitario INET" = 'X' 
union all select 46 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Artística Secundaria"                 = 'X' 
union all select 48 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Artística Superior no Universitario"  = 'X' 
union all select 50 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Artística Cursos y Talleres"          = 'X' 
union all select 23 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Especial Educación Temprana"          = 'X' 
union all select 17 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Especial Inicial"                     = 'X' 
union all select 18 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Especial Primaria"                    = 'X' 
union all select 19 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Especial Secundaria"                  = 'X' 
union all select 24 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Especial Integración"                 = 'X' 
union all select 31 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos Primaria"                     = 'X' 
union all select 39 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos EGB3"                         = 'X' 
union all select 32 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos Secundaria"                   = 'X' 
union all select 40 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos Alfabetizacion"               = 'X' 
union all select 41 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos Formacion Profesional"        = 'X' 
union all select 42 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Adultos Formacion Profesional INET"   = 'X' 
union all select 58 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Hospitalaria Domiciliaria Inicial"    = 'X' 
union all select 59 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Hospitalaria Domiciliaria Primaria"   = 'X' 
union all select 60 as idTN, "CUE Anexo" as Codigo from DatosBase where "Servicios complementarios" = 'X' and "Ed. Hospitalaria Domiciliaria Secundaria" = 'X';